FROM xldenis/hakyll:latest

RUN apt-get update && apt-get install --yes \
    imagemagick \
    make

RUN stack --resolver nightly-2018-06-10 install \
    hakyll-favicon \
    hakyll-sass

EXPOSE 8000

ENTRYPOINT ["bash"]
