version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ .Environment.HAKYLL_VERSION }}
          paths:
            - /caches/
      - run:
          name: Build docker image without extensions
          command: |
            set -euf +o pipefail
            docker load -i /caches/docker-hakyll.tar | true
            docker build --cache-from=xldenis/hakyll:"$HAKYLL_VERSION" -t xldenis/hakyll:"$HAKYLL_VERSION" .
      - run:
          name: Tag latest docker image
          command: docker tag xldenis/hakyll:"$HAKYLL_VERSION" xldenis/hakyll:latest
      - run:
          name: Build docker image with extensions
          command: |
            set -euf +o pipefail
            docker load -i /caches/docker-hakyll-ext.tar | true
            docker build --cache-from=xldenis/hakyll:"$HAKYLL_VERSION"-ext -t xldenis/hakyll:"$HAKYLL_VERSION"-ext -f Dockerfile.ext .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/docker-hakyll.tar xldenis/hakyll:"$HAKYLL_VERSION"
            docker save -o /caches/docker-hakyll-ext.tar xldenis/hakyll:"$HAKYLL_VERSION"-ext
      - save_cache:
          key: v1-{{ .Branch }}-{{ .Environment.HAKYLL_VERSION }}
          paths:
            - /caches/
      - deploy:
          name: Push to Docker Hub
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
              docker push xldenis/hakyll:latest
              docker push xldenis/hakyll:"$HAKYLL_VERSION"
              docker push xldenis/hakyll:"$HAKYLL_VERSION"-ext
            fi
